# Generated by Django 3.2.3 on 2021-06-01 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='country',
            field=models.CharField(default='No_Country', help_text='Select your Country', max_length=50),
        ),
        migrations.RemoveField(
            model_name='company',
            name='country',
        ),
        migrations.AddField(
            model_name='company',
            name='country',
            field=models.CharField(default='No_Country', help_text='Select your Country', max_length=50),
        ),
        migrations.RemoveField(
            model_name='jobseeker',
            name='country',
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='country',
            field=models.CharField(default='No_Country', help_text='Select your Country', max_length=50),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='email',
            field=models.EmailField(error_messages={'unique': 'A user with that email already exists.'}, max_length=254),
        ),
        migrations.DeleteModel(
            name='Country',
        ),
    ]
